##
# Services needed to run Magento2 application on Docker
#
# Docker Compose defines required services and attach them together through aliases
##
version: '2'
services:
    web:
        container_name: proj1-m2web
        restart: always
        image: alankent/magento2devbox-web:latest
        volumes:

          # LEAVE THIS LINE COMMENTED OUT IF YOU ARE USING UNISON.
          # Uncomment to use Docker volume mounts to share files with
          # local file system.
          #- "./shared/www:/var/www"

          # Uncomment to share your ~/.ssh directory with the container.
          # This can be useful for GitHub ssh keys and similar.
          #- "~/.ssh:/home/magento2/.ssh"

          # Uncomment this line if you want to share your composer
          # download cache between projects (more efficient, but
          # means the auth.json file will also be shared).
          #- "~/.composer:/home/magento2/.composer"

          # Uncomment to mount local directory for apache log files.
          #- "./shared/logs/apache2:/var/log/apache2"

          # Uncomment to mount local directory for FPM log files.
          #- "./shared/logs/php-fpm:/var/log/php-fpm"

          # Uncomment to share Magento cloud CLI settings between projects.
          #- "./shared/.magento-cloud:/home/magento2/.magento-cloud"

        environment:
          # Optional. If set, container will create a default auth.json
          # file for Composer to use (if one does not already exist).
          #- MAGENTO_PUBLIC_KEY=<insert-hex-key-here>
          #- MAGENTO_PRIVATE_KEY=<insert-hex-key-here>

        # The following exposes ports inside the container publicly.
        # Docker maps the public port numbers to ports inside the container
        # using Linux iptables support. If a single number is specified,
        # Docker will pick an unused port number at random every time the
        # container restarts. Use 8080:80 to bind the public port number
        # of 8080 to the internal port number of 80. (The internal port
        # number never changes - you may pick any external port number
        # to avoid collisions between different containers or projects.)
        ports:

          # Pick a random unused web server port.
          # (Use 8080:80 for force external port to be 8080.)
          - 80

          # The SSH port.
          - 22

          # Pick a random unused unison port.
          # (Only needed if using Unison for file syncing.)
          - 5000

          # Default BrowserSync ports.
          # (Only needed if using BrowserSync for frontend development.)
          - 3000
          - 3001

    db:
        container_name: proj1-m2db
        restart: always
        image: mysql:5.6

        ports:
          - "3306"

        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento2

        volumes:

          # Uncomment to mount log files locally.
          #- "./shared/logs/mysql:/var/log/mysql"

          # Uncomment if you want the database to last after removing the
          # container. (Not recommended.)
          #- "./shared/db:/var/lib/mysql"

